const ADD_TO_EDIT_LIST = 'ADD_TO_EDIT_LIST';
const REMOVE_FROM_EDIT_LIST = 'REMOVE_FROM_EDIT_LIST';
const EDIT_LIST_ITEM = 'EDIT_LIST_ITEM';

export { ADD_TO_EDIT_LIST, REMOVE_FROM_EDIT_LIST, EDIT_LIST_ITEM }